---
- hosts: all
  become: true

  tasks:
    - include_vars: vars.yml

    - name: check project directory exists
      stat:
        path: '/helloworld'
      register: check_project_dir

    - name: print check
      debug:
        var: check_project_dir


    - name: create project directory
      file:
        path: /helloworld
        state: directory
        owner: 'ansible'
        group: 'ansible'
