# name: CICD

on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    # container:
      # image: cytopia/ansible:2.13
    steps:

      - name: git clone repo
        uses: actions/checkout@v1

      - name: print list files
        run : |
          # ssh-keygen ansible
          mkdir -p ~/.ssh/
          echo Host 185.195.26.130 >> ~/.ssh/config
          echo User ansible >> ~/.ssh/config
          echo IdentityFile ~/.ssh/ansible >> ~/.ssh/config
          ssh-keyscan -t rsa remote_host  >> ~/.ssh/known_hosts
          ls -la ~/.ssh/
          cat ~/.ssh/config
          echo ${{ vars.SSH_KEY }} >  ~/.ssh/ansible
          # cat ansible.pub

      - name: ping server
        run : |
          echo yes >> 185.195.26.130 && echo "open" || echo "close"
          echo "123"
          echo $HOST_IP
          echo ${{ vars.YOU_NAME }}
          echo ${{ vars.HOST_IP }}
         
     
      - name: ansiple deploy
        run : |
          export ANSIBLE_HOST_KEY_CHECKING=False
          export ANSIBLE_FORCE_COLOR=true
          export ANSIBLE_CALLBACK_WHITELIST=profile_tasks
          export ANSIBLE_GATHER_TIMEOUT=60
          export ANSIBLE_TIMEOUT=60
          export ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=120
          export ANSIBLE_PERSISTENT_CONNECT_RETRY_TIMEOUT=30
          export ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=30
          ansible-playbook --private-key=~/.ssh/ansible --user ansible --inventory ansible/inventory ansible/playbook.yml
    

     # - name: build and run
     #   run : docker compose run

     # - name: page nginx accessibility check
     #   run : if curl -s $(hostname -i) | grep Hello; then exit 1; else exit 0; fi
       
     # - name: page django accessibility check
     #   run : if curl -s $(hostname -i):8000 | grep Hello; then exit 1; else exit 0; fi
       
     # - name: page static files accessibility check
     #   run : if curl -s $(hostname -i)/static_files/ | grep Hello; then exit 1; else exit 0; fi
