name: CICD

on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    # container:
      # image: cytopia/ansible:2.13
    steps:

      - name: git clone repo
        uses: actions/checkout@v1

      - name: print list files
        run : |
          ls -la
          pwd

      - name: ping server
        run : |
          echo yes >> 185.195.26.130 && echo "open" || echo "close"
          echo "123"
          echo $HOST_IP
          echo ${{ vars.YOU_NAME }}
          echo ${{ vars.HOST_IP }}
          ansible -i ansible/inventory all -m ping
     
     # - name: ansiple deploy
     #   run : ansible-playbook --private-key ${{ vars.SSH_PRIVATE_KEY }} --user ansible --inventory ansible/inventory ansible/
    

     # - name: build and run
     #   run : docker compose run

     # - name: page nginx accessibility check
     #   run : if curl -s $(hostname -i) | grep Hello; then exit 1; else exit 0; fi
       
     # - name: page django accessibility check
     #   run : if curl -s $(hostname -i):8000 | grep Hello; then exit 1; else exit 0; fi
       
     # - name: page static files accessibility check
     #   run : if curl -s $(hostname -i)/static_files/ | grep Hello; then exit 1; else exit 0; fi
