name: CICD

on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    # container:
      # image: cytopia/ansible:2.13
    steps:

      - name: git clone repo
        uses: actions/checkout@v1

      - name: creating a project archive
        run : |
          tar cvzf project.tar ./*
          gzip project.tar
          
      - name: docker compose down and create backup
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
                   cd ./helloworld
                   docker compose down
                   docker rmi -f $(docker images -aq)
                   mv project.tar ../project.tar_$(date -d "today" +"%Y%m%d%H%M")
                   rm -r *

          
      # - name: executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: mkdir ./helloworld

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "project.tar.gz"
          target: "./helloworld"
          
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
                    cd helloworld
                    gunzip project.tar.gz 
                    tar -xvf project.tar 

      - name: docker compose up
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
                    cd ./helloworld
                    docker compose up -d
                    docker images
                    docker ps
                    docker ps -a
